run:
  timeout: 5m
  tests: false

output:
  formats:
    - format: colored-line-number

linters:
  disable-all: true
  enable:
    # 🔥 basic wajib
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign

    # 🔥 tambahan bagus
    - typecheck
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    # ignore error json marshal (common)
    - linters:
        - errcheck
      text: "Error return value of .*Marshal.* is not checked"

    # ignore context warning kalau belum dipakai
    - linters:
        - staticcheck
      text: "should not use context.Background"

  max-issues-per-linter: 0
  max-same-issues: 0
