services:
  app:
    build: .
    container_name: social-be
    ports:
      - "8283:8283"
    env_file:
      - .env
    # environment:
    #   NAS_SHARE_PATH: //10.3.1.161/GistexAPPDATA/TzuChiApp
    #   NAS_MOUNT_PATH: /mnt/nas
    #   NAS_SHARE_USER: ${NAS_SHARE_USER}
    #   NAS_SHARE_PASSWORD: ${NAS_SHARE_PASSWORD}
    #   NAS_SHARE_DOMAIN: ${NAS_SHARE_DOMAIN}
    privileged: true
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - /mnt/nas:/mnt/nas

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    ports:
      - "16686:16686"   # UI
      - "4318:4318"     # OTLP HTTP
